# usually stored with code, or in a separate repo
apiVersion: apps/v1
# kind - component type
kind: Deployment
metadata:
  name: nginx-deployment
  # label is used by service selector
  labels:
    app: nginx
#deployment spec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
   #pod template
    metadata:
      labels:
        app: nginx
#pod spec
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 8080
# status is generated below by k8s, from etcd
# viewable via `kubectl get deployment nginx-deployment -o yaml > nginx-deployment-result.yml`
