apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  # connects to pods with label app: nginx
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80 # service port, exposed to outside
    targetPort: 8080 # pod port, exposed to service