apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  # default secret type is Opaque
  # other types are documented here: 
  # https://kubernetes.io/docs/concepts/configuration/secret/#secret-types
  # conversion to base64 encoding can be done with `echo -n 'username' | base64`
  # this ensures that the secret has a text representation
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
